### ISSUE TITLE
DB issues on installation

### ISSUE THREAD

**Issue by zdfs** [benjamminf/craft-neo#19]
Not sure if anyone has seen this before:

```sql
CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint. The SQL statement executed was: ALTER TABLE `craft_neoblocks` ADD CONSTRAINT `craft_neoblocks_ownerLocale_fk` FOREIGN KEY (`ownerLocale`) REFERENCES `craft_locales` (`locale`) ON DELETE CASCADE ON UPDATE CASCADE
```

Not sure what to do here.

**Comment by zdfs** [comment]
More information:

```
------------------------
LATEST FOREIGN KEY ERROR
------------------------
2016-05-21 16:04:33 0x700000e61000 Error in foreign key constraint of table zdfs/#sql-83d_336:
 FOREIGN KEY (`ownerLocale`) REFERENCES `craft_locales` (`locale`) ON DELETE CASCADE ON UPDATE CASCADE:
Cannot find an index in the referenced table where the
referenced columns appear as the first columns, or column types
in the table and the referenced table do not match for constraint.
Note that the internal storage type of ENUM and SET changed in
tables created with >= InnoDB-4.1.12, and such columns in old tables
cannot be referenced by such columns in new tables.
Please refer to http://dev.mysql.com/doc/refman/5.7/en/innodb-foreign-key-constraints.html for correct foreign key definition.
```

**Comment by zdfs** [comment]
I'm starting to think this is because i'm using the free version of Craft?

**Comment by benjamminf** [comment]
This is a strange error. Neo should work perfectly fine on the personal version of Craft. It appears there is some mismatch between the `locale` columns between `craft_neoblocks` and `craft_locales` tables. Not sure how or why that's happening. Can you confirm your tables look like these? Specifically, the `locale` and `ownerLocale` columns:

![](http://i.imgur.com/2hLVk87.png)

**Comment by benjamminf** [comment]
Given that no one else has reported this issue, and it's age, I'm going to close this for now. If this was never solved reply back here and I'll reopen it :+1:

**Comment by envas** [comment]
Sorry for re-opening the issue. I got the same error. The error message has been probably raised when installation almost finished because the plugin status was, despite the error, set to `installed`. Unfortunately, the plugin did not work properly. 

In my case, the issue was due to different table collations. My Craft instance, including the table craft_locales, has been installed with the collation utf8_bin. This specific collation is defined in my 'craft/config/db.php' and overrides the Craft default collation defined in 'craft/app/etc/config/defaults/db.php'.  

NEO plugin created all craft_neo* tables with the collation utf8_unicode_ci, Craft default. That's a bug, all plugins should use the non-default collation from the custom db.php, if defined. Probably it's the Craft bug because the Reasons plugin created the table with wrong collation as well. As far as I know, plugin records do not have to deal with database details, the tables are created via the API.

The workaround is to edit the Craft default in 'craft/app/etc/config/defaults/db.php' before the plugin installation. With updated default db.php the installation was successful.
