### ISSUE TITLE
Revert to version 

### ISSUE THREAD

**Issue by sidneywidmer** [benjamminf/craft-neo#23]
Hey benjammin,

I just noticed that you can't revert an entry to a previous version, the Neo field is just empty. Is this a known bug? Do you think this feature will be available in the near future?

Cheerio
Sidney

**Comment by christianruhstaller** [comment]
It seems that it works fine.
Only the display of the data when going back to a version isn't working.
If you revert this version back as the current entry, the data from the version get's filled correctly. 

In the fieldType the corresponding function getStaticHtml and it's rendering need to be updated.

**Comment by benjamminf** [comment]
Hey @sidneywidmer , sorry for the late response. Under the pump at the moment getting a project completed by Monday so I haven't had the time to check this out (as well as finish fixing some of the other bug reports). This is embarrassingly not something I checked. I don't think I've ever used the versioning system in Craft.

Thankfully, @christianruhstaller is right - it seems to just be cosmetic. In order to keep template redundancy low, templates are rendered in Javascript, which obviously is a problem in this case.

I'll be onto this after this week.

**Comment by benjamminf** [comment]
Done. Thanks @christianruhstaller for your fix, it helped me out a lot. This will be available in the next release, which will be released mid-late next week.
