### ISSUE TITLE
Blank Tabs

### ISSUE THREAD

**Issue by AbbeyDesign** [benjamminf/craft-neo#32]
In some cases, I would like the first tab in a block to be blank. For example I have a block called "row". It has options, but this block is just a simple container for child blocks and the options are rarely used. I don't want to see them all while adding new rows. In the field layout I create a tab with no fields in it and then another tab with all the optional fields.

When I go back to an entry, this is not respected. Then when I go back to the NEO field settings, the first blank tab I created is gone.

**Comment by benjamminf** [comment]
Hey David, yeah this is a feature I myself have been really wanting. Since I'm using the field layout designer API provided by Craft, I don't have a lot (or really any) control over how the field layouts are saved. So it's actually Craft's fault it's stripping out the blank tabs - try it on an entry type and it'll do the same thing.

I'm not sure if I can trick Craft into keeping empty tabs, but if I can't I've been thinking of having another lightswitch option on each block type to allow you to treat the child blocks section as a tab.

**Comment by AbbeyDesign** [comment]
Not a huge deal... on the "would be nice" list. Great plugin so far!

**Comment by benjamminf** [comment]
Decided to have a quick look into this just then... turns out it's actually very easy to trick Craft into keeping blank tabs! I'll be releasing this feature in `1.3.0`, or possibly in a `1.2.3` release if I decide to break the `1.3.0` release up.

**Comment by benjamminf** [comment]
This has been implemented, and will be available in the `1.3.0` release.
