### ISSUE TITLE
Duplicate a whole Neo field? Possible "Field Manager" support?

### ISSUE THREAD

**Issue by BryceBubbles** [benjamminf/craft-neo#33]
A field has to be unique within a section in Craft right? So it's not possible to have a Neo field in a "main content" tab, and then another instance of the same field in a "sidebar" or "footer" tab on the same section.

I tried cloning a Neo field with [Field Manager](https://github.com/engram-design/FieldManager). While the clone was successfully created, all the fields were removed from the original Neo field (silly me should have done a DB backup right before trying this, but I'm sure I can work out how to reassign them back to the original in the DB).

So my question is - how might I go about reusing a Neo field on the same section?
- Is there an easy way I'm unaware of perhaps? Is duplication the only way?
- Could Neo work with Field Manager? Would that be handled on your end, or Josh Crawford's?
- Or could a duplicate/clone option be added to the Neo field settings page? Probably a pretty extreme option?

Thanks

**Comment by benjamminf** [comment]
Hey Bryce,

> how might I go about reusing a Neo field on the same section?

Unfortunately due to how Craft is built, there's no way you can do this. One field per field layout, since fields are referenced using their handles, you'd have clashes with multiples of the same field.

> Is there an easy way I'm unaware of perhaps? Is duplication the only way?

Duplication really is the only way to use the "same" field multiple times in a single field layout.

> Could Neo work with Field Manager? Would that be handled on your end, or Josh Crawford's?

I haven't used Field Manager before, and I'm not sure how it works under the hood, so I can't say for sure if I'll be able to add support on my end or not. My educated guess is Josh would need to add support for it in his own plugin.

The issue with the original losing all it's fields after duplication leads me to believe the Field Manager plugin simply copies a field's settings object when duplicating it. Because Neo fields rely on multiple tables of data for single field, there's a lot of linked data in a field's settings. So what probably happened is that the block types and field layouts were being pointed to from now _two_ fields, and the newer field won out over the older one. As a side note, I'm fairly sure if you had removed the newly created Neo field's row from the `craft_fields` table (and make sure to ignore any constraints, so deletion cascades wouldn't run, deleting all your block types, field layouts and content) everything would have gone back to normal.

Duplicating a Neo field would require duplicating not just the field itself, but also all it's block types, groups and field layouts. This would probably need to be handled by the Field Manager plugin using a special case for Neo fields.

> Or could a duplicate/clone option be added to the Neo field settings page? Probably a pretty extreme option?

I think this is something that's a bit outside the scope of Neo. Ideally, Craft could implement as "Save as new" button for fields like they do with entries, which would accomplish this. It might actually be a decent idea for a small plugin... hmm...

Personally I think Neo fields are pretty quick to create as they are, considering it's mostly just composing field layouts of existing fields. Duplicating even a large Neo field manually wouldn't take any more than a couple of minutes, and it's not something that you would be doing very often anyway.

Phew, sorry about the wall of text!

**Comment by benjamminf** [comment]
Actually, I should point out this plugin, which can do what you're after (albeit in a roundabout way): https://github.com/Pennebaker/craftcms-thearchitect

It supports Neo fields, so what you can do is run an export on your current site, isolate the Neo field JSON declaration, give it a new handle (and name if you want), and re-import it back into the site.

**Comment by BryceBubbles** [comment]
Woh, thanks for the quick and detailed reply.
- Yeah I made a DB backup and then deleted the cloned field rows and all is well.
- I'll give Josh a holler to see what he thinks about supporting Neo fields, but yeah it would be quite extreme to clone all it's block types, groups and field layouts.
- I had seen The Architect plugin and have been meaning to try it out, so I'll give it a go.
Cheers
