### ISSUE TITLE
Max Child Blocks

### ISSUE THREAD

**Issue by spAnser** [benjamminf/craft-neo#42]
We can limit blocks by type but it would be nice to limit child blocks to a set number to allow a choice of which blocks they want to use.

Currently if I have 3 child blocks I can set a max of 3 to each meaning they can get up to 9 child blocks. If I set 1 max to each type they can only use 3 but have to use one of each.

**Comment by benjamminf** [comment]
I agree, this would be a useful feature. As mentioned in #40, there's a lot of other rule-based options that would be useful too, so I've been thinking of ways to incorporate them all in a UI-friendly way, which is why I haven't added this one in yet. But it comes up a lot so I'll add it in sooner than later.

**Comment by benjamminf** [comment]
Now implemented in 1.4.0 which is currently still in testing. If you're interested you can grab the early release from the master branch.

**Comment by spAnser** [comment]
Nice will do next week.
