### ISSUE TITLE
Always prompted to leave/stay

### ISSUE THREAD

**Issue by ianshea** [benjamminf/craft-neo#45]
Having a super minor issue with the javascript prompt for Staying/Leaving showing up without any changes actually made.

**Comment by benjamminf** [comment]
Stupid question but are you running at least version 1.3.1 or greater? [I actually fixed this issue in 1.3.1](https://github.com/benjamminf/craft-neo/releases/tag/1.3.1) and can't seem to reproduce this in later versions. Otherwise, can you tell me what the specs are of your environment? (Browser as well as Craft & PHP version) Thanks

**Comment by ianshea** [comment]
No prob! I'm running Neo 1.3.3. Running Craft CMS 2.6.2903, PHP 5.6.10.

Chrome Version 52.0.2743.116 (64-bit)
Safari Version 9.1.2 (11601.7.7)

I'm on my local box using Mamp. So I did a quick switch to PHP 7.0.8 and I still see the issue.

However, I'm **not** seeing the issue in Firefox 45.0.1 or 48.0. So this is most likely a webkit thing... I'll see if I can debug a bit more on this.

**Comment by ianshea** [comment]
Okay, little more info. I've got a bunch of Rich Text redactor fields in my setup, and removing any  blocks containing those fields seems to alleviate this particular issue. So I think this may be related to #44

**Comment by benjamminf** [comment]
Unfortunately I'm still unable to reproduce this issue. I've tried on the same version of Chrome on both Windows and OSX, and with a variety of different rich text fields, and I can't get it to trip up. I have released a new version (1.3.4) which has made changes to the way resources are loaded for blocks, so it's *possible* this could solve the issue, but I doubt it. Nevertheless, give it a try and let me know how it goes.

**Comment by AbbeyDesign** [comment]
Funny, just posted same issue on Slack. I have the latest version 1.3.4 and I get it on Chrome. Not Firefox or Safari, just Chrome. I had this happen once on another site, but it eventually went away. In both cases I suspect it started when I added a dropdown field(after weeks without issue), then changed the options in the dropdown field(including the default value).

**Comment by AbbeyDesign** [comment]
Just to clarify, I also had RichText fields in my NEO, but the issue only popped up once I added and started messing around with a dropdown.

**Comment by fyrebase** [comment]
I can confirm Neo 1.3.4 and Chrome 52.0.2743.116 prompts when leaving and a dropdown / select is present. I can give you a DB dump if it helps @benjamminf

**Comment by benjamminf** [comment]
This is so bizzare. I've figured out what's causing it and it's so stupid.

Turns out it has something to only do with Redactor 1 & 2 (I've tried other rich text editors like Froala and it doesn't do this). It happens *only* when you have *multiple paragraphs* of content in a Redactor field, and even then it only happens in *some* situations (which I haven't quite pinpointed yet...)

This is such a weird bug, and I'm honestly at a loss as to how and why this is happening. Anyway, at least I've been able to replicate it.

**Comment by ianshea** [comment]
@benjamminf Can you point out in the codebase on where it's happening? I might be able to fit in some troubleshooting this week to help out.

**Comment by benjamminf** [comment]
@ianshea thanks for the offer, but I've figured it out. My guess was correct - Redactor is filtering out white-space which is playing with the modification detection script. Neo actually has it's own modification detection, which is used to bypass saving individual blocks if they haven't changed. This was getting tricked, which caused it to change a hidden "modification flag" field, which in turn tricked Craft's own modification detection.

Aaaanyway, I just moved where Neo takes it's snapshot to after this white-space removal, and now it's all working :+1:
