### ISSUE TITLE
Multi locale Matrix Blocks - Blocks and content deleted on save

### ISSUE THREAD

**Issue by rubenwebs** [benjamminf/craft-neo#46]
Hi,

I have an issue with a Neo Field that consists of 3 block types.
And each block type has a matrix field in it.
The Neo Field and the matrix fields are all set on translatable.

![screen1](https://cloud.githubusercontent.com/assets/5013717/17591846/2ff6643e-5fe0-11e6-8849-1da679a60415.png)

The two locales are NL (Dutch) and EN (English), with dutch as the primary.

If I add a block for the first time in the Neo field on the English locale, then the matrix field in it has the Dutch locale enabled. See the screenshot, the locale EN for the field is displayed and the matrix block is set to NL instead of EN.

![screen2](https://cloud.githubusercontent.com/assets/5013717/17591868/4f8f4a18-5fe0-11e6-847f-26523085b763.png)

If I add in some matrix blocks with content, all blocks and the content inside are deleted on save. The next screen shows the result after saving:

![screen3](https://cloud.githubusercontent.com/assets/5013717/17591902/71593faa-5fe0-11e6-9db3-18fe5dd8e915.png)

So the locales of the matrix blocks are now set to the right one: EN. And if I add in matrix blocks, now it gets saved.

Have an Idea to fix this?

With kind regards,
Ruben

**Comment by benjamminf** [comment]
Hey Ruben, sorry you're having trouble here. Localisation is actually fairly complex when it comes to nested fields in Craft, and not even Craft itself has solved it. The Matrix field actually suffers from the same behaviour. This happens when you separately enable localisation on fields inside Matrix/Neo blocks, and also on the Matrix/Neo field itself. Since Neo simply leverages Craft's API's to render fields based on locale, I regret to say that this is a core Craft issue and that I cannot fix it.

The solution is typically to disable localization on either the Matrix/Neo field itself, or on the fields within the blocks. The difference between each option is that in the former case, you can add/remove/reorder blocks per locale, whereas in the latter, you can't.

**Comment by benjamminf** [comment]
This issue got me thinking how I could allow this with Neo, and I'm pleased to report that I've figured out a way to "trick" Craft into allowing nesting of localised fields. It's not recommended that this be used (if you're localising the whole Neo field then you shouldn't localise the fields inside the blocks) but if you don't have a choice, I've figured out a way to allow it.
