### ISSUE TITLE
Plugin causing JS alerts from garnish.js (Version 1.3.5 )

### ISSUE THREAD

**Issue by mtnorthrop** [benjamminf/craft-neo#50]
I've just upgraded to version 1.3.5, and now, when I open an entry that uses Neo, I see this alert in the Chrome JS console: "Double-instantiating a transparent text input on an element" - garnish.js:6535

I'm not sure this is actually causing a problem with the plugin's functionality, but the notice was not there before.

**Comment by ladrua** [comment]
I am also seeing this, what problems are you experiencing? We have some issues with row in supertable not being saved..

**Comment by benjamminf** [comment]
Sorry for the late response. The console log is just a minor warning by Garnish that doesn't really affect anything. In certain situations some Garnish components are being initialised twice, but Garnish picks up on it and handles it. This happens usually because when Neo blocks are created, Neo initialises all Garnish components inside the block, but some fields will explicitly initialise their components as well. So sometimes you get these warnings, but everything still functions normally.
