### ISSUE TITLE
Check if field exists

### ISSUE THREAD

**Issue by pl-mnm** [benjamminf/craft-neo#51]
Hi, I'm trying to check if a field exists in a neo block. I'm following [this suggestion](http://craftcms.stackexchange.com/a/9623/576) (but for a matrix field) and I can't get it to work:

```
{% for block in blocks.level(1) %}
  {% if block['foo'] is defined %}
    yep
  {% else %}
    nope
  {% endif %}
{% endfor %}
```
It will output 'true' if the field exists anywhere in Craft, even if its not present in the block. Am I missing something? 

Thanks in advance.

**Comment by benjamminf** [comment]
How Craft works is that every element is given a field as a property as long as that field is in the same context of the element. What this means is that because Neo fields use existing fields (the "global" context) each block is implicitly given the property of every globally defined field. This sounds weird, but it's how entries, categories, etc. all work as well. And there's likely good reasons for this - for example, you might have noticed unassigning a field from an entry type still lets you access the values those fields once stored. It's an opportunity to undo what you've done without losing data in the process.

The reason this works for Matrix blocks though, is that they're a special case - each block type is given it's own context. For Neo, the easiest way would be to change `if block['foo'] is defined` to `if block.foo is not empty`. This is not exactly one-to-one but practically it shouldn't make a difference.

**Comment by pl-mnm** [comment]
Aha! This actually answers some questions I had regarding Craft (like why all CP fields appear in the logs). Thanks for that, and thanks for your work on all your plugins, great stuff.

**Comment by missmatsuko** [comment]
@benjamminf Wondering if there is another solution to checking if a Neo block can use a field? Checking if the field is not empty errors out for me because the field doesn't exist (callout here is a lightswitch field). 

Code:
```
{% set isCallout = item.callout is not empty and item.callout %}
```

Result:
```
Craft\MatrixBlockModel and its behaviors do not have a method or closure named "callout".
```
