### ISSUE TITLE
Static Supertables

### ISSUE THREAD

**Issue by smockensturm** [benjamminf/craft-neo#64]
I don't think Neo template code is prepared to parse a static Super Table.

For example, this works as expected (assume we are looping through Neo blocks):

    {% for row in block.superTable %}
        {{ row.somehandle }}
    {% endfor %}

BUT, if we turn on Super Table's **Static Field** ("A static field will only display a single row of fields.") and use this template code:

    {{ block.superTable.somehandle }}

No go. ERROR: Object of class Craft\ElementCriteriaModel could not be converted to string

For your convenience, here is a link to Super Table template examples:

https://github.com/engram-design/SuperTable/wiki/Templating-examples

**Comment by smockensturm** [comment]
why this issue get no love?

**Comment by benjamminf** [comment]
Hey @smockensturm, sorry I haven't been around. I've been extremely busy for the last few months and am currently overseas for work. I've been going through the issues one by one when I have time, just haven't gotten to this one yet. I'd probably have to talk to Josh about this as I'm not sure where the issue lies in this one. I'll keep you posted.

**Comment by SimonEast** [comment]
@smockensturm - have you tried looping through the field like in the first example? 

```
{% for row in block.superTable %}
    {{ row.somehandle }}
{% endfor %}
```

Perhaps for some reason it's still in an array format instead of a single var? (I have not tested this, just attempting to troubleshoot with you.)

Otherwise if you can debug the `{{ block.superTable.somehandle }}` object, there might be a way to access it's data.

**Comment by smockensturm** [comment]
@SimonEast Yes. Thank you. Oh that works. For sure. I think I mentioned that in the post. :)

This is a control panel experience thing. I'd like to use Super Table as advertised (regarding **Static Field**, i.e. don't show the user  " + Add a Column" at the bottom. I know we can limit the rows to 1, but the prompt is still visible / grayed out.) Using **Static Field** we _don't_ get that prompt in the CP.

But apparently Neo cannot handle the single line template code as advertised by Super Table regarding **Static Field**.

**Comment by benjamminf** [comment]
@smockensturm This may be a silly question but have you made sure the "Static field" lightswitch is on? If you're still seeing the "+ Add a column" button in the CP then that's most likely your issue. I have a static Super Table field inside a Neo block and it's working as advertised.

**Comment by smockensturm** [comment]
We're good here. I'm a dope. Thanks, Ben.

**Comment by benjamminf** [comment]
Haha all good, glad it's working 👍
